openapi: 3.2.0
info:
  title: Quandoo Public Partner Status API
  description: The Quandoo Public Partner API is a multi-purpose REST API for the Quandoo restaurant reservations platform.
  version: 1.0.0
  contact:
    name: Quandoo Developers
    email: developers@quandoo.com
    url: https://docs.quandoo.com/
servers:
- url: https://public-api.prod.quandoo.com
  description: Production
security:
- API_TOKEN: []
tags:
- name: Status
paths:
  /v1/status:
    get:
      tags:
      - Status
      summary: Quandoo Provides Information on the Status of the Service
      operationId: getStatusByGet_1
      responses:
        '200':
          description: OK
        '500':
          description: Internal server error
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  securitySchemes:
    API_TOKEN:
      type: apiKey
      name: X-Quandoo-AuthToken
      in: header
